server:
  port: 8090
spring:
  datasource:
    url: jdbc:mysql://imikasa.com:3307/lnfvc
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/*.xml

uploadImgPath: /root/stu_photoes