server:
  port: 8090
spring:
  datasource:
    url: jdbc:mysql://imikasa.com:3309/lnfvc
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/mapper.xml
  config-location: classpath:mapper/mapper-config.xml
#  configuration:
#    map-underscore-to-camel-case: true

#uploadImgPath: /root/stu_photoes
uploadImgPath: D:\temp\photos